"""
UI string translations for RoadSoS.
Supported languages: English, Tamil, Hindi, Telugu, Kannada
"""

LANG_OPTIONS = {
    "en": "English",
    "ta": "Tamil — தமிழ்",
    "hi": "Hindi — हिंदी",
    "te": "Telugu — తెలుగు",
    "kn": "Kannada — ಕನ್ನಡ",
}

STRINGS = {
    "en": {
        "tagline":           "AI-powered emergency assistant · Road accident response · Works offline · 45+ countries",
        "metric_label":      "Verified contacts in DB",
        "sidebar_settings":  "Settings",
        "groq_key_label":    "Groq API Key (free)",
        "groq_key_help":     "Get free key at console.groq.com — enables AI understanding",
        "ai_active":         "AI mode active",
        "no_api_info":       "Works without API key using smart rules",
        "radius_label":      "Search radius (km)",
        "lang_label":        "Language",
        "lang_detected":     "Auto-detected:",
        "always_reliable":   "Always reliable:",
        "input_header":      "Describe the Emergency",
        "input_label":       "What happened? Where?",
        "input_placeholder": "e.g.  Accident near Hosur on NH-44, one person injured and unconscious",
        "gps_label":         "Or enter GPS coordinates directly:",
        "lat_label":         "Latitude",
        "lon_label":         "Longitude",
        "find_help_btn":     "Find Emergency Help",
        "tier1_header":      "Always Call These First — 100% Reliable",
        "tier1_caption":     "Government-mandated, 24x7, works anywhere in India",
        "spinner_intent":    "Understanding your emergency...",
        "urgency_label":     "Urgency",
        "calling_label":     "Calling",
        "spinner_locate":    "Locating...",
        "located_msg":       "Located",
        "no_location":       "Couldn't pinpoint location — showing national numbers only.",
        "spinner_search":    "Searching nearby emergency contacts...",
        "gh_header":         "Golden Hour Score",
        "callorder_critical_hw":  "Call order: 1. 112 (all services)  ->  2. 1033 (NHAI)  ->  3. 108 (ambulance)",
        "callorder_critical":     "Call order: 1. 112 (national emergency)  ->  2. 108 (ambulance)",
        "callorder_puncture":     "Call order: 1. 1033 (NHAI if on highway)  ->  nearest towing/puncture shop below",
        "callorder_medium":       "Call order: 1. 1033 (NHAI helpline)  ->  nearest service below",
        "contacts_found":    "Contacts Found (within {r} km)",
        "no_phone":          "No phone number listed — use 112 as fallback",
        "confidence_label":  "Confidence",
        "source_label":      "Source",
        "low_conf_warning":  "Low confidence — try 112 if this doesn't connect",
        "btn_worked":        "Worked",
        "btn_failed":        "Failed",
        "feedback_ok":       "Updated!",
        "feedback_fail":     "Reported!",
        "no_contacts":       "No local contacts found. National numbers above work everywhere.",
        "share_header":      "Share with Family",
        "share_caption":     "Tap to send location + nearest contacts to family in one tap",
        "no_input":          "Please type a message or enter GPS coordinates to find emergency help.",
        "footer1":           "Global emergency numbers supported",
        "footer2":           "Offline-ready for 66 National Highways",
        "footer3":           "No data stored externally",
        "verified":          "Verified",
        "likely_ok":         "Likely OK",
        "unverified":        "Unverified",
        "gh_green_msg":      "Help ~{eta} min away — golden hour is safe",
        "gh_green_advice":   "Call 108. Stay calm. Keep victim still.",
        "gh_amber_msg":      "Estimated ~{eta} min — act quickly",
        "gh_amber_advice":   "Call 108 immediately. Start first aid if trained. Don't move spinal injuries.",
        "gh_red_msg":        "~{eta} min — outside golden hour window",
        "gh_red_advice":     "CALL 112 NOW. If safe, begin transport to nearest hospital.",
    },

    "ta": {
        "tagline":           "AI-ஆல் இயங்கும் அவசரகால உதவியாளர் · சாலை விபத்து · ஆஃப்லைனில் செயல்படும் · 45+ நாடுகள்",
        "metric_label":      "DB-யில் சரிபார்க்கப்பட்ட தொடர்புகள்",
        "sidebar_settings":  "அமைப்புகள்",
        "groq_key_label":    "Groq API Key (இலவசம்)",
        "groq_key_help":     "console.groq.com-ல் இலவச key பெறவும் — AI புரிதலை இயக்கும்",
        "ai_active":         "AI முறை செயலில் உள்ளது",
        "no_api_info":       "API key இல்லாமலும் smart rules மூலம் செயல்படும்",
        "radius_label":      "தேடல் ஆரம் (கிமீ)",
        "lang_label":        "மொழி",
        "lang_detected":     "தானாக கண்டறியப்பட்டது:",
        "always_reliable":   "எப்போதும் நம்பகமானவை:",
        "input_header":      "அவசரநிலையை விவரிக்கவும்",
        "input_label":       "என்ன நடந்தது? எங்கே?",
        "input_placeholder": "எ.கா. NH-44ல் Hosur அருகில் விபத்து, ஒருவர் காயமடைந்து மயக்கமாக உள்ளார்",
        "gps_label":         "அல்லது GPS நிரலங்களை நேரடியாக உள்ளிடவும்:",
        "lat_label":         "அட்சரேகை",
        "lon_label":         "தீர்க்கரேகை",
        "find_help_btn":     "அவசரகால உதவி தேடு",
        "tier1_header":      "இவற்றை முதலில் அழைக்கவும் — 100% நம்பகமானவை",
        "tier1_caption":     "அரசு கட்டாயமாக்கியவை, 24x7, இந்தியா முழுவதும் செயல்படும்",
        "spinner_intent":    "உங்கள் அவசரநிலையை புரிந்துகொள்கிறோம்...",
        "urgency_label":     "அவசரம்",
        "calling_label":     "அழைக்க வேண்டியவை",
        "spinner_locate":    "இடத்தை கண்டறிகிறோம்...",
        "located_msg":       "இடம் கண்டறியப்பட்டது",
        "no_location":       "இடத்தை துல்லியமாக கண்டறிய முடியவில்லை — தேசிய எண்களை மட்டும் காட்டுகிறோம்.",
        "spinner_search":    "அருகிலுள்ள அவசரகால தொடர்புகளை தேடுகிறோம்...",
        "gh_header":         "கோல்டன் அவர் நிலை",
        "callorder_critical_hw":  "அழைப்பு வரிசை: 1. 112 (அனைத்து சேவைகள்)  ->  2. 1033 (NHAI)  ->  3. 108 (ஆம்புலன்ஸ்)",
        "callorder_critical":     "அழைப்பு வரிசை: 1. 112 (தேசிய அவசரநிலை)  ->  2. 108 (ஆம்புலன்ஸ்)",
        "callorder_puncture":     "அழைப்பு வரிசை: 1. 1033 (நெடுஞ்சாலையில் இருந்தால்)  ->  அருகிலுள்ள towing கடை",
        "callorder_medium":       "அழைப்பு வரிசை: 1. 1033 (NHAI helpline)  ->  அருகிலுள்ள சேவை",
        "contacts_found":    "{r} கிமீ உள்ளே கண்டறியப்பட்ட தொடர்புகள்",
        "no_phone":          "தொலைபேசி எண் இல்லை — 112 அழைக்கவும்",
        "confidence_label":  "நம்பகத்தன்மை",
        "source_label":      "ஆதாரம்",
        "low_conf_warning":  "நம்பகத்தன்மை குறைவு — இணைக்க முடியாவிட்டால் 112 அழைக்கவும்",
        "btn_worked":        "வேலை செய்தது",
        "btn_failed":        "வேலை செய்யவில்லை",
        "feedback_ok":       "புதுப்பிக்கப்பட்டது!",
        "feedback_fail":     "புகார் பதிவு செய்யப்பட்டது!",
        "no_contacts":       "அருகில் தொடர்புகள் இல்லை. மேலே உள்ள தேசிய எண்கள் எங்கும் செயல்படும்.",
        "share_header":      "குடும்பத்தினருக்கு பகிரவும்",
        "share_caption":     "இடம் மற்றும் அருகிலுள்ள தொடர்புகளை குடும்பத்தினருக்கு ஒரே தட்டுதலில் அனுப்பவும்",
        "no_input":          "அவசரகால உதவி தேட செய்தி தட்டச்சு செய்யுங்கள் அல்லது GPS நிரலங்களை உள்ளிடுங்கள்.",
        "footer1":           "உலக அவசரகால எண்கள் ஆதரவு",
        "footer2":           "66 தேசிய நெடுஞ்சாலைகளுக்கு ஆஃப்லைன் தயார்",
        "footer3":           "வெளியில் எந்த தரவும் சேமிக்கப்படவில்லை",
        "verified":          "சரிபார்க்கப்பட்டது",
        "likely_ok":         "சரியாக இருக்கும்",
        "unverified":        "சரிபார்க்கப்படவில்லை",
        "gh_green_msg":      "உதவி ~{eta} நிமிடத்தில் — கோல்டன் அவர் பாதுகாப்பானது",
        "gh_green_advice":   "108 அழைக்கவும். அமைதியாக இருங்கள். பாதிக்கப்பட்டவரை அசைக்காதீர்கள்.",
        "gh_amber_msg":      "தோராயமாக ~{eta} நிமிடம் — விரைவாக செயல்படுங்கள்",
        "gh_amber_advice":   "உடனே 108 அழைக்கவும். முதலுதவி தெரிந்தால் செய்யுங்கள். முதுகெலும்பு காயம் இருந்தால் அசைக்காதீர்கள்.",
        "gh_red_msg":        "~{eta} நிமிடம் — கோல்டன் அவர் கடந்துவிடும்",
        "gh_red_advice":     "உடனே 112 அழைக்கவும். பாதுகாப்பாக இருந்தால் அருகில் மருத்துவமனைக்கு கொண்டு செல்லுங்கள்.",
    },

    "hi": {
        "tagline":           "AI-संचालित आपातकालीन सहायक · सड़क दुर्घटना प्रतिक्रिया · ऑफलाइन कार्य करता है · 45+ देश",
        "metric_label":      "DB में सत्यापित संपर्क",
        "sidebar_settings":  "सेटिंग्स",
        "groq_key_label":    "Groq API Key (निःशुल्क)",
        "groq_key_help":     "console.groq.com पर निःशुल्क key प्राप्त करें — AI समझ सक्षम करता है",
        "ai_active":         "AI मोड सक्रिय",
        "no_api_info":       "API key के बिना भी smart rules से काम करता है",
        "radius_label":      "खोज त्रिज्या (किमी)",
        "lang_label":        "भाषा",
        "lang_detected":     "स्वतः पहचाना गया:",
        "always_reliable":   "हमेशा विश्वसनीय:",
        "input_header":      "आपातस्थिति बताएं",
        "input_label":       "क्या हुआ? कहां?",
        "input_placeholder": "जैसे NH-44 पर Hosur के पास दुर्घटना, एक व्यक्ति घायल और बेहोश है",
        "gps_label":         "या GPS निर्देशांक सीधे दर्ज करें:",
        "lat_label":         "अक्षांश",
        "lon_label":         "देशांतर",
        "find_help_btn":     "आपातकालीन सहायता खोजें",
        "tier1_header":      "इन्हें पहले कॉल करें — 100% विश्वसनीय",
        "tier1_caption":     "सरकार अनिवार्य, 24x7, पूरे भारत में काम करता है",
        "spinner_intent":    "आपकी आपातस्थिति समझ रहे हैं...",
        "urgency_label":     "तात्कालिकता",
        "calling_label":     "कॉल करें",
        "spinner_locate":    "स्थान खोज रहे हैं...",
        "located_msg":       "स्थान मिला",
        "no_location":       "सटीक स्थान नहीं मिला — केवल राष्ट्रीय नंबर दिखा रहे हैं।",
        "spinner_search":    "पास के आपातकालीन संपर्क खोज रहे हैं...",
        "gh_header":         "गोल्डन आवर स्थिति",
        "callorder_critical_hw":  "कॉल क्रम: 1. 112 (सभी सेवाएं)  ->  2. 1033 (NHAI)  ->  3. 108 (एम्बुलेंस)",
        "callorder_critical":     "कॉल क्रम: 1. 112 (राष्ट्रीय आपातकाल)  ->  2. 108 (एम्बुलेंस)",
        "callorder_puncture":     "कॉल क्रम: 1. 1033 (राजमार्ग पर हों तो)  ->  पास का towing",
        "callorder_medium":       "कॉल क्रम: 1. 1033 (NHAI helpline)  ->  पास की सेवा",
        "contacts_found":    "{r} किमी के भीतर संपर्क मिले",
        "no_phone":          "फ़ोन नंबर नहीं है — 112 पर कॉल करें",
        "confidence_label":  "विश्वसनीयता",
        "source_label":      "स्रोत",
        "low_conf_warning":  "कम विश्वसनीयता — कनेक्ट न हो तो 112 करें",
        "btn_worked":        "काम किया",
        "btn_failed":        "काम नहीं किया",
        "feedback_ok":       "अपडेट हो गया!",
        "feedback_fail":     "रिपोर्ट हो गया!",
        "no_contacts":       "पास में कोई संपर्क नहीं मिला। ऊपर के राष्ट्रीय नंबर हर जगह काम करते हैं।",
        "share_header":      "परिवार को भेजें",
        "share_caption":     "एक टैप में स्थान और पास के संपर्क परिवार को भेजें",
        "no_input":          "सहायता खोजने के लिए संदेश टाइप करें या GPS निर्देशांक दर्ज करें।",
        "footer1":           "वैश्विक आपातकालीन नंबर समर्थित",
        "footer2":           "66 राष्ट्रीय राजमार्गों के लिए ऑफलाइन तैयार",
        "footer3":           "बाहर कोई डेटा संग्रहीत नहीं",
        "verified":          "सत्यापित",
        "likely_ok":         "संभवतः ठीक",
        "unverified":        "असत्यापित",
        "gh_green_msg":      "मदद ~{eta} मिनट में — गोल्डन आवर सुरक्षित",
        "gh_green_advice":   "108 कॉल करें। शांत रहें। पीड़ित को हिलाएं नहीं।",
        "gh_amber_msg":      "अनुमानित ~{eta} मिनट — जल्दी करें",
        "gh_amber_advice":   "तुरंत 108 कॉल करें। प्राथमिक चिकित्सा करें। रीढ़ की चोट हो तो न हिलाएं।",
        "gh_red_msg":        "~{eta} मिनट — गोल्डन आवर खतरे में",
        "gh_red_advice":     "अभी 112 कॉल करें। सुरक्षित हो तो नजदीकी अस्पताल ले जाएं।",
    },

    "te": {
        "tagline":           "AI-ఆధారిత అత్యవసర సహాయకుడు · రోడ్డు ప్రమాద స్పందన · ఆఫ్‌లైన్‌లో పని చేస్తుంది · 45+ దేశాలు",
        "metric_label":      "DB లో ధృవీకరించిన సంప్రదింపులు",
        "sidebar_settings":  "సెట్టింగ్‌లు",
        "groq_key_label":    "Groq API Key (ఉచితం)",
        "groq_key_help":     "console.groq.com లో ఉచిత key పొందండి — AI అవగాహన సక్రియం చేస్తుంది",
        "ai_active":         "AI మోడ్ సక్రియంగా ఉంది",
        "no_api_info":       "API key లేకుండా కూడా smart rules తో పని చేస్తుంది",
        "radius_label":      "శోధన వ్యాసార్థం (కిమీ)",
        "lang_label":        "భాష",
        "lang_detected":     "స్వయంచాలకంగా గుర్తించబడింది:",
        "always_reliable":   "ఎల్లప్పుడూ నమ్మదగినవి:",
        "input_header":      "అత్యవసర పరిస్థితిని వివరించండి",
        "input_label":       "ఏం జరిగింది? ఎక్కడ?",
        "input_placeholder": "ఉదా. NH-44 పై Hosur దగ్గర ప్రమాదం, ఒక వ్యక్తి గాయపడి స్పృహ కోల్పోయారు",
        "gps_label":         "లేదా GPS కోఆర్డినేట్లు నేరుగా నమోదు చేయండి:",
        "lat_label":         "అక్షాంశం",
        "lon_label":         "రేఖాంశం",
        "find_help_btn":     "అత్యవసర సహాయం కనుగొనండి",
        "tier1_header":      "ఇవి ముందుగా కాల్ చేయండి — 100% నమ్మదగినవి",
        "tier1_caption":     "ప్రభుత్వ నిర్బంధం, 24x7, భారతదేశం అంతటా పని చేస్తుంది",
        "spinner_intent":    "మీ అత్యవసర పరిస్థితిని అర్థం చేసుకుంటున్నాం...",
        "urgency_label":     "అత్యవసరత",
        "calling_label":     "కాల్ చేయాల్సినవి",
        "spinner_locate":    "స్థానాన్ని గుర్తిస్తున్నాం...",
        "located_msg":       "స్థానం గుర్తించబడింది",
        "no_location":       "ఖచ్చితమైన స్థానం గుర్తించలేకపోయాం — జాతీయ నంబర్లు మాత్రమే చూపిస్తున్నాం.",
        "spinner_search":    "సమీప అత్యవసర సంప్రదింపులు శోధిస్తున్నాం...",
        "gh_header":         "గోల్డన్ అవర్ స్థితి",
        "callorder_critical_hw":  "కాల్ క్రమం: 1. 112 (అన్ని సేవలు)  ->  2. 1033 (NHAI)  ->  3. 108 (అంబులెన్స్)",
        "callorder_critical":     "కాల్ క్రమం: 1. 112 (జాతీయ అత్యవసరం)  ->  2. 108 (అంబులెన్స్)",
        "callorder_puncture":     "కాల్ క్రమం: 1. 1033 (హైవేపై ఉంటే)  ->  సమీప towing",
        "callorder_medium":       "కాల్ క్రమం: 1. 1033 (NHAI helpline)  ->  సమీప సేవ",
        "contacts_found":    "{r} కిమీ లోపు సంప్రదింపులు కనుగొనబడ్డాయి",
        "no_phone":          "ఫోన్ నంబర్ లేదు — 112 కి కాల్ చేయండి",
        "confidence_label":  "నమ్మకత",
        "source_label":      "మూలం",
        "low_conf_warning":  "తక్కువ నమ్మకత — కనెక్ట్ కాకపోతే 112 కాల్ చేయండి",
        "btn_worked":        "పని చేసింది",
        "btn_failed":        "పని చేయలేదు",
        "feedback_ok":       "అప్‌డేట్ అయింది!",
        "feedback_fail":     "నివేదించబడింది!",
        "no_contacts":       "దగ్గర్లో సంప్రదింపులు లేవు. పై జాతీయ నంబర్లు అన్నిచోట్లా పని చేస్తాయి.",
        "share_header":      "కుటుంబానికి పంపండి",
        "share_caption":     "ఒక్క టాప్‌తో స్థానం మరియు సమీప సంప్రదింపులు కుటుంబానికి పంపండి",
        "no_input":          "సహాయం కనుగొనడానికి సందేశం టైప్ చేయండి లేదా GPS కోఆర్డినేట్లు నమోదు చేయండి.",
        "footer1":           "గ్లోబల్ అత్యవసర నంబర్లు మద్దతు ఉంది",
        "footer2":           "66 జాతీయ రహదారులకు ఆఫ్‌లైన్ సిద్ధం",
        "footer3":           "బయటకు డేటా నిల్వ చేయబడలేదు",
        "verified":          "ధృవీకరించబడింది",
        "likely_ok":         "బహుశా సరే",
        "unverified":        "ధృవీకరించబడలేదు",
        "gh_green_msg":      "సహాయం ~{eta} నిమిషాల్లో — గోల్డన్ అవర్ సురక్షితం",
        "gh_green_advice":   "108 కాల్ చేయండి. శాంతంగా ఉండండి. బాధితుడిని కదపకండి.",
        "gh_amber_msg":      "అంచనా ~{eta} నిమిషాలు — వేగంగా వ్యవహరించండి",
        "gh_amber_advice":   "వెంటనే 108 కాల్ చేయండి. ప్రథమ చికిత్స తెలిస్తే చేయండి. వెన్నెముక గాయానికి కదపకండి.",
        "gh_red_msg":        "~{eta} నిమిషాలు — గోల్డన్ అవర్ విండో దాటింది",
        "gh_red_advice":     "ఇప్పుడే 112 కాల్ చేయండి. సురక్షితమైతే సమీప ఆసుపత్రికి తీసుకెళ్ళండి.",
    },

    "kn": {
        "tagline":           "AI-ಚಾಲಿತ ತುರ್ತು ಸಹಾಯಕ · ರಸ್ತೆ ಅಪಘಾತ ಪ್ರತಿಕ್ರಿಯೆ · ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ · 45+ ದೇಶಗಳು",
        "metric_label":      "DB ನಲ್ಲಿ ಪರಿಶೀಲಿತ ಸಂಪರ್ಕಗಳು",
        "sidebar_settings":  "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        "groq_key_label":    "Groq API Key (ಉಚಿತ)",
        "groq_key_help":     "console.groq.com ನಲ್ಲಿ ಉಚಿತ key ಪಡೆಯಿರಿ — AI ತಿಳುವಳಿಕೆ ಸಕ್ರಿಯಗೊಳಿಸುತ್ತದೆ",
        "ai_active":         "AI ಮೋಡ್ ಸಕ್ರಿಯವಾಗಿದೆ",
        "no_api_info":       "API key ಇಲ್ಲದೆಯೂ smart rules ಮೂಲಕ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ",
        "radius_label":      "ಹುಡುಕಾಟ ತ್ರಿಜ್ಯ (ಕಿಮೀ)",
        "lang_label":        "ಭಾಷೆ",
        "lang_detected":     "ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಪತ್ತೆಯಾಯಿತು:",
        "always_reliable":   "ಯಾವಾಗಲೂ ವಿಶ್ವಾಸಾರ್ಹ:",
        "input_header":      "ತುರ್ತು ಪರಿಸ್ಥಿತಿಯನ್ನು ವಿವರಿಸಿ",
        "input_label":       "ಏನಾಯಿತು? ಎಲ್ಲಿ?",
        "input_placeholder": "ಉದಾ. NH-44 ನಲ್ಲಿ Hosur ಬಳಿ ಅಪಘಾತ, ಒಬ್ಬ ವ್ಯಕ್ತಿ ಗಾಯಗೊಂಡು ಪ್ರಜ್ಞಾಹೀನರಾಗಿದ್ದಾರೆ",
        "gps_label":         "ಅಥವಾ GPS ನಿರ್ದೇಶಾಂಕಗಳನ್ನು ನೇರವಾಗಿ ನಮೂದಿಸಿ:",
        "lat_label":         "ಅಕ್ಷಾಂಶ",
        "lon_label":         "ರೇಖಾಂಶ",
        "find_help_btn":     "ತುರ್ತು ಸಹಾಯ ಹುಡುಕಿ",
        "tier1_header":      "ಇವುಗಳನ್ನು ಮೊದಲು ಕರೆಯಿರಿ — 100% ವಿಶ್ವಾಸಾರ್ಹ",
        "tier1_caption":     "ಸರ್ಕಾರ ಕಡ್ಡಾಯ, 24x7, ಭಾರತದಾದ್ಯಂತ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ",
        "spinner_intent":    "ನಿಮ್ಮ ತುರ್ತು ಪರಿಸ್ಥಿತಿಯನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳುತ್ತಿದ್ದೇವೆ...",
        "urgency_label":     "ತುರ್ತು",
        "calling_label":     "ಕರೆ ಮಾಡಿ",
        "spinner_locate":    "ಸ್ಥಳ ಪತ್ತೆಹಚ್ಚುತ್ತಿದ್ದೇವೆ...",
        "located_msg":       "ಸ್ಥಳ ಪತ್ತೆಯಾಯಿತು",
        "no_location":       "ನಿಖರ ಸ್ಥಳ ಪತ್ತೆಹಚ್ಚಲಾಗಲಿಲ್ಲ — ರಾಷ್ಟ್ರೀಯ ಸಂಖ್ಯೆಗಳನ್ನು ಮಾತ್ರ ತೋರಿಸುತ್ತಿದ್ದೇವೆ.",
        "spinner_search":    "ಹತ್ತಿರದ ತುರ್ತು ಸಂಪರ್ಕಗಳನ್ನು ಹುಡುಕುತ್ತಿದ್ದೇವೆ...",
        "gh_header":         "ಗೋಲ್ಡನ್ ಅವರ್ ಸ್ಥಿತಿ",
        "callorder_critical_hw":  "ಕರೆ ಕ್ರಮ: 1. 112 (ಎಲ್ಲ ಸೇವೆಗಳು)  ->  2. 1033 (NHAI)  ->  3. 108 (ಆಂಬ್ಯುಲೆನ್ಸ್)",
        "callorder_critical":     "ಕರೆ ಕ್ರಮ: 1. 112 (ರಾಷ್ಟ್ರೀಯ ತುರ್ತು)  ->  2. 108 (ಆಂಬ್ಯುಲೆನ್ಸ್)",
        "callorder_puncture":     "ಕರೆ ಕ್ರಮ: 1. 1033 (ಹೆದ್ದಾರಿಯಲ್ಲಿದ್ದರೆ)  ->  ಹತ್ತಿರದ towing",
        "callorder_medium":       "ಕರೆ ಕ್ರಮ: 1. 1033 (NHAI helpline)  ->  ಹತ್ತಿರದ ಸೇವೆ",
        "contacts_found":    "{r} ಕಿಮೀ ಒಳಗಿನ ಸಂಪರ್ಕಗಳು ಕಂಡುಬಂದಿವೆ",
        "no_phone":          "ಫೋನ್ ನಂಬರ್ ಇಲ್ಲ — 112 ಗೆ ಕರೆ ಮಾಡಿ",
        "confidence_label":  "ವಿಶ್ವಾಸಾರ್ಹತೆ",
        "source_label":      "ಮೂಲ",
        "low_conf_warning":  "ಕಡಿಮೆ ವಿಶ್ವಾಸಾರ್ಹತೆ — ಸಂಪರ್ಕ ಆಗದಿದ್ದರೆ 112 ಕರೆ ಮಾಡಿ",
        "btn_worked":        "ಕೆಲಸ ಮಾಡಿತು",
        "btn_failed":        "ಕೆಲಸ ಮಾಡಲಿಲ್ಲ",
        "feedback_ok":       "ನವೀಕರಿಸಲಾಗಿದೆ!",
        "feedback_fail":     "ವರದಿ ಮಾಡಲಾಗಿದೆ!",
        "no_contacts":       "ಹತ್ತಿರದಲ್ಲಿ ಸಂಪರ್ಕಗಳಿಲ್ಲ. ಮೇಲಿನ ರಾಷ್ಟ್ರೀಯ ನಂಬರ್‌ಗಳು ಎಲ್ಲೆಡೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತವೆ.",
        "share_header":      "ಕುಟುಂಬಕ್ಕೆ ಕಳುಹಿಸಿ",
        "share_caption":     "ಒಂದೇ ಟ್ಯಾಪ್‌ನಲ್ಲಿ ಸ್ಥಳ ಮತ್ತು ಹತ್ತಿರದ ಸಂಪರ್ಕಗಳನ್ನು ಕುಟುಂಬಕ್ಕೆ ಕಳುಹಿಸಿ",
        "no_input":          "ಸಹಾಯ ಹುಡುಕಲು ಸಂದೇಶ ಟೈಪ್ ಮಾಡಿ ಅಥವಾ GPS ನಿರ್ದೇಶಾಂಕ ನಮೂದಿಸಿ.",
        "footer1":           "ಜಾಗತಿಕ ತುರ್ತು ಸಂಖ್ಯೆಗಳು ಬೆಂಬಲಿತ",
        "footer2":           "66 ರಾಷ್ಟ್ರೀಯ ಹೆದ್ದಾರಿಗಳಿಗೆ ಆಫ್‌ಲೈನ್ ಸಿದ್ಧ",
        "footer3":           "ಯಾವುದೇ ಡೇಟಾ ಹೊರಗೆ ಸಂಗ್ರಹಿಸಲ್ಪಡುವುದಿಲ್ಲ",
        "verified":          "ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
        "likely_ok":         "ಬಹುಶಃ ಸರಿ",
        "unverified":        "ಪರಿಶೀಲಿಸಲಾಗಿಲ್ಲ",
        "gh_green_msg":      "ಸಹಾಯ ~{eta} ನಿಮಿಷದಲ್ಲಿ — ಗೋಲ್ಡನ್ ಅವರ್ ಸುರಕ್ಷಿತ",
        "gh_green_advice":   "108 ಕರೆ ಮಾಡಿ. ಶಾಂತವಾಗಿರಿ. ಸಂತ್ರಸ್ತರನ್ನು ಅಲುಗಾಡಿಸಬೇಡಿ.",
        "gh_amber_msg":      "ಅಂದಾಜು ~{eta} ನಿಮಿಷ — ತ್ವರಿತವಾಗಿ ಕಾರ್ಯನಿರ್ವಹಿಸಿ",
        "gh_amber_advice":   "ತಕ್ಷಣ 108 ಕರೆ ಮಾಡಿ. ಪ್ರಥಮ ಚಿಕಿತ್ಸೆ ತಿಳಿದಿದ್ದರೆ ಮಾಡಿ. ಬೆನ್ನುಮೂಳೆ ಗಾಯಕ್ಕೆ ಅಲುಗಾಡಿಸಬೇಡಿ.",
        "gh_red_msg":        "~{eta} ನಿಮಿಷ — ಗೋಲ್ಡನ್ ಅವರ್ ಮೀರಿದೆ",
        "gh_red_advice":     "ಈಗಲೇ 112 ಕರೆ ಮಾಡಿ. ಸುರಕ್ಷಿತವಾಗಿದ್ದರೆ ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗೆ ಕರೆದೊಯ್ಯಿರಿ.",
    },
}


def detect_lang_from_script(text: str) -> str:
    """Detect language from Unicode character ranges — no API needed."""
    for char in text:
        cp = ord(char)
        if 0x0B80 <= cp <= 0x0BFF: return "ta"   # Tamil
        if 0x0900 <= cp <= 0x097F: return "hi"   # Devanagari (Hindi)
        if 0x0C00 <= cp <= 0x0C7F: return "te"   # Telugu
        if 0x0C80 <= cp <= 0x0CFF: return "kn"   # Kannada
    return "en"


# Multi-language emergency keywords for rule-based fallback
CRITICAL_KEYWORDS = {
    "ta": ["ரத்தம்", "மயக்கம்", "மூச்சில்லை", "தீ", "இறந்து"],
    "hi": ["खून", "बेहोश", "सांस नहीं", "आग", "मर रहा"],
    "te": ["రక్తం", "స్పృహ కోల్పోయారు", "శ్వాస లేదు", "నిప్పు", "చనిపోతున్నారు"],
    "kn": ["ರಕ್ತ", "ಮೂರ್ಛೆ", "ಉಸಿರಿಲ್ಲ", "ಬೆಂಕಿ", "ಸಾಯುತ್ತಿದ್ದಾರೆ"],
}

HIGH_KEYWORDS = {
    "ta": ["காயம்", "விபத்து", "மோதல்", "சேதம்"],
    "hi": ["घायल", "दुर्घटना", "टक्कर", "चोट"],
    "te": ["గాయపడిన", "ప్రమాదం", "ఢీకొన్న", "గాయం"],
    "kn": ["ಗಾಯ", "ಅಪಘಾತ", "ಡಿಕ್ಕಿ", "ಗಾಯಗೊಂಡ"],
}
